---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: repository
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
    - role: role_under_test
      openio_redis_namespace: "{{ NS }}"
      openio_redis_bind_address: "{{ ansible_default_ipv4.address }}"
...
