# roles/redis/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_redis_namespace }}"
    - path: "{{ openio_redis_sysconfig_dir }}/{{ openio_redis_servicename }}"
    - path: "{{ openio_redis_volume }}"
    - path: "{{ openio_redis_pid_directory }}"
    - path: "/var/log/oio/sds/{{ openio_redis_namespace }}/{{ openio_redis_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0770"
  tags: install

- name: Ensure Redis pid directory is persistant
  lineinfile:
    dest: /etc/tmpfiles.d/redis.conf
    create: true
    line: "d {{ openio_redis_pid_directory }} 755 openio openio -"
    owner: openio
    group: openio
    mode: 0644
  tags: install
  when: openio_redis_pid_directory.split(' ')[0] | dirname is match("/run/.*")

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "{{ openio_redis_type }}.conf.j2"
      dest: "{{ openio_redis_sysconfig_dir }}/\
        {{ openio_redis_servicename }}/{{ openio_redis_type }}.conf"
    - src: "gridinit_redis.conf.j2"
      dest: "{{ openio_redis_gridinit_dir }}/{{ openio_redis_gridinit_file_prefix }}\
        {{ openio_redis_servicename }}.conf"
  register: _redis_conf

- name: restart redis
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_redis_namespace }}-{{ openio_redis_servicename }}
  when:
    - _redis_conf.changed
    - not openio_redis_provision_only
  tags: configure
...
